version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend-instance:/app/instance
    environment:
      - FLASK_APP=labelgen:create_app
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://backend:5000
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend-instance:
